server:
  port: 8086

spring:
  application:
    name: pos-service
  datasource:
    url: jdbc:postgresql://localhost:5432/pos_db
    username: erpadmin
    password: erpadmin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

jwt:
  secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
  expiration: 86400000

services:
  inventory:
    url: http://localhost:8082

pos:
  cart:
    ttl-minutes: 30
  price-cache:
    ttl-minutes: 60