server:
  port: 8084

spring:
  application:
    name: finance-service
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_db
    username: erpadmin
    password: erpadmin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: finance-service
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      enable-auto-commit: false

jwt:
  secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
  expiration: 86400000